# Generated by Django 2.2 on 2020-12-26 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201226_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be AlphaNumeric or contain any of the following regex: [.@#]*$]', regex='^[a-zA-Z0-9.#]*$')]),
        ),
    ]
