# Generated by Django 2.2 on 2020-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_show', '0003_auto_20201222_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshow',
            name='data_added',
        ),
        migrations.AddField(
            model_name='movieshow',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
