# Generated by Django 2.2 on 2020-12-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_show', '0004_auto_20201222_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='date_added',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
